---
- include_tasks: dependencies_install.yml

- name: Select query to mysql with named_args
  community.mysql.mysql_query:
    login_host: '{{ mysql_host }}'
    login_db: '{{ mysql_db }}'
    login_port: '{{ mysql_port }}'
    login_user: '{{ mysql_user }}'
    login_password: '{{ mysql_password }}'
    query: select hostname, port, username, password from dbauthentication where db = 'mssqlserver'
  register: creds

## for debug testing
# - name: credential info debug only
#   debug:
#     msg: '{{ creds.query_result[0] }}'

- include_tasks: process_query_result.yml
  loop: "{{ creds.query_result[0] }}"

